### PR TITLE
fix(block): make `inner` aware of title positions

### LINKED ISSUE #658: bottom-positioned title in block with bottom border prevents rendering of paragraph content when drawing area has height 2
## Description

Rendering a block with title and border at the bottom in an area of height 2 makes the associated paragraphs' content disappear.

## To Reproduce

``` rust
let block = Block::default()
    .title("Title")
    .title_position(Position::Bottom)
    .borders(Borders::BOTTOM);
let paragraph = Paragraph::new("Hello, world!").block(block);

let area = Rect::new(0, 0, 15, 2);
let mut buffer = Buffer::empty(area);
paragraph.render(area, &mut buffer);
println!("{buffer:?}");
```

```
Buffer {
    …
    content: [
        "               ",
        "Title──────────",
    ],
    …
}
```

## Expected behavior

```
Buffer {
    …
    content: [
        "Hello, world!  ",
        "Title──────────",
    ],
    …
}
```

## Environment

- Crate version: 0.24.1-alpha.5

Since I'm using the `ratatui::buffer::Buffer` in the minimal working example, I feel like other environment information is not necessary. Please let me know if that assumption is incorrect.

## Additional context

- A fix is proposed in #657

### PR DESCRIPTION
**Pull request by jan-ferdinand**
Previously, when computing the inner rendering area of a block, all titles were assumed to be positioned at the top. If some or all titles were at the bottom, this caused various incorrect computations of the inner area, depending on which borders were set; no border at the bottom would lead to an area that's too big, no border at the top but at the bottom and _all_ titles at the bottom would lead to an area that's too small.

Now, when computing the inner area, the positions of the titles are taken into account.

fix #658

### CODE REVIEW

**Review by orhun — COMMENTED** [review]
Can you also add a test case where you cover the issue in #658? (you can assert the contents of the buffer with `assert_buffer`)

**Comment by jan-ferdinand** [comment]
> add a test case where you cover the issue in #658

Good suggestion. I have amended the PR accordingly. Let me know if anything can be improved. :relaxed:

File: src/widgets/block.rs [hunk 1]
```diff
@@ -532,6 +533,16 @@ impl<'a> Block<'a> {
...
     }
 
+    fn have_title_at_position(&self, position: Position) -> bool {
+        if self.titles.iter().any(|t| t.position == Some(position)) {
+            return true;
+        }
+        if self.titles.iter().any(|t| t.position.is_none()) {
+            return self.titles_position == position;
+        }
+        false
```
Comment (joshka) [inline src/widgets/block.rs:543]: slightly simpler (nit):

```suggestion
        self.titles
            .iter()
            .any(|title|
                title.position == Some(position)
                || title.position.is_none() && self.titles_position == position)
```

**Review by joshka — APPROVED** [review]
Can you please suggest a simple and concise explanation of the bug?
If you're able, add it to the body of a commit message to make it automatically fill the changelog. If not, we can add the wording when squashing the commit.

File: src/widgets/block.rs (hunk 1 above)
Comment (jan-ferdinand) [reply src/widgets/block.rs:543]: How about:

``` rust
        self.titles.iter().any(|title| match title.position {
            Some(title_position) => title_position == position,
            None => self.titles_position == position,
        })
```

**Comment by jan-ferdinand** [comment]
I have added an explanation of the bug and the fix to both the description of this PR and the commit message. Let me know should brevity be lacking, or if the level of detail could be improved upon (in either direction).

Also, I have reworked the part that @joshka had a nit about, without accepting the suggestion. If you prefer to have your suggestion exactly, I'll incorporate that instead.

File: src/widgets/block.rs (hunk 1 above)
Comment (joshka) [reply src/widgets/block.rs]: Good idea, but you could go one step futher still: :)
```rust
self.titles.iter.any(|title| position == title_position.unwrap_or(self.titles_position))
```

**Review by joshka — APPROVED** [review]

**Comment by jan-ferdinand** [comment]
Thanks for the shortened bug description as well as the improved code snippet. :+1: I've incorporated both and amended the PR accordingly.

**Comment by orhun** [comment]
Thanks for your contribution!
