### PR TITLE
fix(terminal): fix inline viewport resizing issues by clearing the screen

### LINKED ISSUE #2086: Resize for inline viewport
## Description
Inline viewport resizing doesn't seem to behave well (as been also pointed out by @joshka in https://github.com/ratatui/ratatui/pull/1964#issuecomment-3138834123 in the context of inline viewport resizing PR).

## To Reproduce
Run the following and resize the terminal horizontally:
```rust
use color_eyre::Result;
use ratatui::{
    DefaultTerminal, Frame, TerminalOptions, Viewport,
    crossterm::event::{self, Event, KeyCode},
    widgets::{Block, Paragraph},
};

fn main() -> Result<()> {
    color_eyre::install()?;
    let terminal = ratatui::init_with_options(TerminalOptions {
        viewport: Viewport::Inline(8),
    });
    let app_result = run(terminal);
    ratatui::restore();
    app_result
}

fn run(mut terminal: DefaultTerminal) -> Result<()> {
    loop {
        terminal.draw(hello_world)?;
        match event::read()? {
            Event::Key(key) => {
                if key.kind == event::KeyEventKind::Press && key.code == KeyCode::Char('q') {
                    break;
                }
            }
            Event::Resize(_w, _h) => terminal.autoresize()?,
            _ => (),
        }
    }
    Ok(())
}

fn hello_world(frame: &mut Frame) {
    frame.render_widget(
        Paragraph::new("Hello World!").block(Block::bordered().title("Greeting")),
        frame.area(),
    );
}
```

## Screenshots
If run within zellij (which is run within ghostty):
Image

If run straight within ghostty:
Image

## Environment
- OS: macOS
- Terminal Emulator: ghostty
- Crate version: latest main
- Backend: crossterm

### PR DESCRIPTION
**Pull request by wyvernbw**
## About

follow up to the discussion in #2349 

adds a check to the autoresize function to clear the entire screen and move the inline viewport to the top when the window shrinks horizontally in order to avoid line wrapping issues.

Other libraries like ink purge the history as well, but the `backend::ClearType` type does not support that. Without this if the user scrolls up they will see previous broken renders. This should work well with all terminal emulators and multiplexers.

## Todo

- [x] tests

fixes #2086

### CODE REVIEW

File: ratatui-core/src/terminal/resize.rs [hunk 1]
```diff
@@ -32,6 +32,13 @@ impl<B: Backend> Terminal<B> {
             }
             Viewport::Fixed(_) | Viewport::Fullscreen => area,
         };
+
+        // clear screen on horizontal shrink to avoid line wrapping issues
+        if next_area.width < self.viewport_area.width {
+            next_area.y = 0;
+            self.backend.clear_region(crate::backend::ClearType::All)?;
```
Comment (orhun) [inline ratatui-core/src/terminal/resize.rs]: nit: import this at the top:

```suggestion
            self.backend.clear_region(ClearType::All)?;
```

File: ratatui-core/src/terminal/resize.rs [hunk 2]
```diff
@@ -252,4 +259,38 @@ mod tests {
 
         assert_eq!(terminal.viewport_area, Rect::new(0, 0, 10, 3));
     }
+
+    #[test]
+    fn resize_inline_clears_screen_on_horizontal_shrink() {
+        // this tests for the case where the new width is smaller than the old
+        // with. the screen should be cleared completely to avoid rendering
+        // glitches caused by line wrap.
+
```
Comment (orhun) [inline ratatui-core/src/terminal/resize.rs]:
```suggestion
    // This tests for the case where the new width is smaller than the old
    // width.The screen should be cleared completely to avoid rendering
    // glitches caused by line wrap.
    #[test]
    fn resize_inline_clears_screen_on_horizontal_shrink() {
```

**Comment by wyvernbw** [comment]
thanks for the review, fixed
