### PR TITLE
fix(barchart): fix(barchart): use width() instead of len() to get unicode string length

### LINKED ISSUE #513: Barchart doesn't render labels in entire width
## Description

The barchart widget doesn't render labels that are the full width (this affects both non-unicode and unicode)

## To Reproduce

```rust
fn render_simple_barchart(area: Rect, buf: &mut Buffer) {
    let data = [
        ("Sat", 76),
        ("Sun", 69),
        ("Mon", 65),
        ("Tue", 67),
        ("Wed", 65),
        ("Thu", 69),
        ("Fri", 73),
    ];
    let data = data
        .into_iter()
        .map(|(label, value)| {
            Bar::default()
                .value(value)
                // cannot use this until the column width bug is fixed
                .text_value(format!("{}°", value))
                .label(label.into())
        })
        .collect_vec();
    let group = BarGroup::default().bars(&data);
    BarChart::default()
        .data(group)
        .bar_width(3)
        .bar_gap(1)
        .render(area, buf);
}
```

image

with the following line removed:

```rust
                .text_value(format!("{}°", value))
```
image

And the same occurs replacing that with 
```rust
                .text_value(format!("{}x", value))
```

## Expected behavior
I think this should probably render like the following (hacking a couple of things in the barchart implementation to make it work):

image

## Environment
Mac/iterm/FiraCode(NF)/main/crossterm

## Additional context
- Is this expected behavior for some historical reason?
- If this is expected, how should it be documented?
- What significance should unicode play here (e.g. the degree symbol has string len = 2 and unicode width = 1)? Is #75 relevant to the degree symbol?
- What is the history of this? Check for any guidance from commits, and comments on PRs/ issues in Ratatui and tui-rs.

### PR DESCRIPTION
**Pull request by karthago1**
value_label.len() deliver byte length of the unicode strings, which are
not printed as a result.

use witdh() instead.

### CODE REVIEW

File: src/widgets/barchart/bar.rs [hunk 1]
```diff
@@ -155,7 +155,7 @@ impl<'a> Bar<'a> {
             };
 
             let width = value_label.len() as u16;
-            if width < max_width {
+            if width <= max_width {
```
Comment (kdheepak) [inline src/widgets/barchart/bar.rs:158]: I think this is not going to do the right thing in all instances?

For example, can you add a test where one of the labels is `"🤦🏼‍♂️".into()`?

Comment (karthago1) [reply src/widgets/barchart/bar.rs]: I reverted the comparison back to `<` , but I am using width() instead

**Review by joshka — APPROVED** [review]
LGTM - we can merge this and work out the rest of the problem in #513 with small values.

**Comment by joshka** [comment]
I updated the commit message a bit to make it more Changelog friendly and merged this. Thanks for the PR @karthago1
