### PR TITLE
fix(line): line truncation respects alignment

### LINKED ISSUE #932: Line truncation should respect alignment
## Description
A left aligned line should truncate the right side
A right aligned line should truncate the left side
A center aligned line should truncate both sides

## To Reproduce
First test passes, others don't
```rust
        #[test]
        fn render_truncates_left() {
            let mut buf = Buffer::empty(Rect::new(0, 0, 5, 1));
            Line::from("Hello world").left_aligned().render(buf.area, &mut buf);
            let expected = Buffer::with_lines(vec!["Hello     "]);
            assert_buffer_eq!(buf, expected);
        }

        #[test]
        fn render_truncates_right() {
            let mut buf = Buffer::empty(Rect::new(0, 0, 5, 1));
            Line::from("Hello world").right_aligned().render(buf.area, &mut buf);
            let expected = Buffer::with_lines(vec!["     world"]);
            assert_buffer_eq!(buf, expected);
        }

        #[test]
        fn render_truncates_center() {
            let mut buf = Buffer::empty(Rect::new(0, 0, 5, 1));
            Line::from("Hello world").centered().render(buf.area, &mut buf);
            let expected = Buffer::with_lines(vec!["lo wo"]);
        }
```

## Expected behavior
Truncate right aligned and centered lines

## Environment

- OS:
- Terminal Emulator:
- Font:
- Crate version: 0.26
- Backend:

### PR DESCRIPTION
**Pull request by TadoTheMiner**
When rendering a `Line`, the line will be truncated:
- on the right for left aligned lines
- on the left for right aligned lines
- on bot sides for centered lines

E.g. "Hello World" will be rendered as "Hello", "World", "lo wo" for
left, right, centered lines respectively.

Fixes: https://github.com/ratatui-org/ratatui/issues/932

### CODE REVIEW

**Comment by TadoTheMiner** [comment]
> ## [Codecov](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org) Report
> 
> Attention: Patch coverage is `97.33333%` with `2 lines` in your changes are missing coverage. Please review.
> 
> > Project coverage is 92.0%. Comparing base [(`c56f49b`)](https://app.codecov.io/gh/ratatui-org/ratatui/commit/c56f49b9fb1c7f1c8c97749119e85f81882ca9a9?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org) to head [(`1b6946e`)](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?dropdown=coverage&src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org).
> 
> > ❗ Current head [1b6946e](https://github.com/ratatui-org/ratatui/commit/1b6946efa4d1666d3f86b6979585b8b4d12c5a77) differs from pull request most recent head [2722f05](https://github.com/ratatui-org/ratatui/commit/2722f05b732ab74f898c97c40513b346d129977c). Consider uploading reports for the commit [2722f05](https://github.com/ratatui-org/ratatui/commit/2722f05b732ab74f898c97c40513b346d129977c) to get more accurate results
> 
> [Files](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org) 	Patch % 	Lines
> [src/text/line.rs](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org#diff-c3JjL3RleHQvbGluZS5ycw==) 	97.3% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org)
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/ratatui-org/ratatui/pull/987?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ratatui-org).

What the bot wants from me?

**Review by orhun — APPROVED** [review]

File: src/text/line.rs [hunk 1]
```diff
@@ -451,6 +451,40 @@ impl<'a> Line<'a> {
...
+            Some(Alignment::Center) => (width.saturating_sub(result_width)) / 2,
+            Some(Alignment::Right) => width.saturating_sub(result_width),
+            _ => 0,
+        };
+        let mut x = 0;
+        for span in &self.spans {
+            let span_width = span.width() as u16;
+            if offset >= span_width {
+                offset -= span_width;
+                continue;
```
Comment (EdJoPaTo) [inline src/text/line.rs:470]: It might be a good idea to add a test case where this code is relevant. I see myself in the future touching and breaking code specifics like this accidentally.

File: src/text/line.rs [hunk 2]
```diff
@@ -451,6 +451,40 @@ impl<'a> Line<'a> {
     pub fn iter_mut(&mut self) -> std::slice::IterMut<Span<'a>> {
         self.spans.iter_mut()
     }
+
+    /// Returns a line that's truncated corresponding to it's alignment and result width
+    #[must_use = "method moves the value of self and returns the modified value"]
```
Comment (EdJoPaTo) [inline src/text/line.rs:456]: Not something entirely specific to this PR as it’s in other places too…

The ownership of the original object is not moved so the message is confusing with ownership in mind.

It actually does not change the value of self and returns a new, modified value. With a lifetime reference shared with the original.

Not sure how often these must_use messages are misleading in other places too… maybe we should create an issue about it to check that?

File: src/text/line.rs [hunk 3]
```diff
@@ -451,6 +451,40 @@ impl<'a> Line<'a> {
...
+            let span_width = span.width() as u16;
+            if offset >= span_width {
+                offset -= span_width;
+                continue;
+            }
+            let mut new_span = span.clone();
+            let new_span_width = span_width - offset;
+            if x + new_span_width > result_width {
+                new_span.content =
+                    Cow::from(&span.content[offset as usize..(result_width - x + offset) as usize]);
```
Comment (EdJoPaTo) [inline src/text/line.rs:476]: It might be a good idea to move the begin / end variables out of this line into their own variables to have more readable code?

File: src/text/line.rs (hunk 2 above)
Comment (joshka) [reply src/text/line.rs:456]: #995

File: src/text/line.rs [hunk 4]
```diff
@@ -453,6 +453,39 @@ impl<'a> Line<'a> {
         self.spans.iter_mut()
     }
 
+    /// Returns a line that's truncated corresponding to it's alignment and result width
+    #[must_use = "method returns the modified value"]
+    pub fn truncated(&'a self, result_width: u16) -> Self {
```
Comment (joshka) [inline src/text/line.rs:458]: I think I'd prefer this to be private for now. The feature is useful, but the name of this method likely shouldn't be `truncated`. It is more similar to the `split_at` (and other related) functions on str, than to the `truncate` method (which implies deletion of characters from a mutable value).

**Review by joshka — CHANGES_REQUESTED** [review]

**Review by joshka — APPROVED** [review]

**Comment by joshka** [comment]
Merged - thanks for the effort in this PR!

**Comment by TadoTheMiner** [comment]
> Merged - thanks for the effort in this PR!

You're welcome
