### PR TITLE
fix(core): avoid cursor position queries during resize

### LINKED ISSUE #2483: Rendering fails due to Ratatui and the app race `stdin`
## Description

While testing https://github.com/ratatui/ratatui/pull/2480 against the latest `main` branch, I hit a crash during rendering when the terminal is resized:

<details><summary>Details</summary>
<p>

```sh
Error: The cursor position could not be read within a normal duration

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1: std::backtrace_rs::backtrace::trace_unsynchronized::<<std::backtrace::Backtrace>::create::{closure#0}>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2: <std::backtrace::Backtrace>::create
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/backtrace.rs:331:13
   3: <anyhow::Error as core::convert::From<std::io::error::Error>>::from
   4: from_residual<yazi_shared::data::data::Data, std::io::error::Error, anyhow::Error>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:2189:27
   5: render
             at ./yazi-fm/src/app/render.rs:31:15
   6: {async_fn#0}
             at ./yazi-fm/src/app/app.rs:52:11
   7: {closure#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/local.rs:1072:44
   8: {closure#0}<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::task::local::{impl#10}::poll::{closure_env#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/local.rs:823:13
   9: try_with<tokio::task::local::LocalData, tokio::task::local::{impl#4}::with::{closure_env#0}<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::task::local::{impl#10}::poll::{closure_env#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>>, core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:462:12
  10: with<tokio::task::local::LocalData, tokio::task::local::{impl#4}::with::{closure_env#0}<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::task::local::{impl#10}::poll::{closure_env#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>>, core::task::poll::Poll<core::result::Result<(), anyhow::Error>>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:426:20
  11: with<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::task::local::{impl#10}::poll::{closure_env#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/local.rs:821:17
  12: poll<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/local.rs:1062:22
  13: {async_fn#0}<yazi::app::app::{impl#0}::serve::{async_fn_env#0}>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/local.rs:719:19
  14: {async_block#0}
             at ./yazi-fm/src/main.rs:43:54
  15: poll<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:133:9
  16: {closure#0}<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/park.rs:284:71
  17: with_budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/coop/mod.rs:167:5
  18: budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/task/coop/mod.rs:133:5
  19: block_on<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/park.rs:284:31
  20: block_on<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/context/blocking.rs:66:14
  21: {closure#0}<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/scheduler/multi_thread/mod.rs:92:22
  22: enter_runtime<tokio::runtime::scheduler::multi_thread::{impl#0}::block_on::{closure_env#0}<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>, core::result::Result<(), anyhow::Error>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/context/runtime.rs:65:16
  23: block_on<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/scheduler/multi_thread/mod.rs:91:9
  24: block_on_inner<core::pin::Pin<alloc::boxed::Box<yazi::main::{async_block_env#0}, alloc::alloc::Global>>>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/runtime.rs:373:50
  25: block_on<yazi::main::{async_block_env#0}>
             at /Users/ika/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.51.1/src/runtime/runtime.rs:343:18
  26: main
             at ./yazi-fm/src/main.rs:43:54
  27: call_once<fn() -> core::result::Result<(), anyhow::Error>, ()>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  28: __rust_begin_short_backtrace<fn() -> core::result::Result<(), anyhow::Error>, core::result::Result<(), anyhow::Error>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166:18
  29: {closure#0}<core::result::Result<(), anyhow::Error>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:206:18
  30: <&dyn core::ops::function::Fn<(), Output = i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe as core::ops::function::FnOnce<()>>::call_once
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/core/src/ops/function.rs:287:21
  31: std::panicking::catch_unwind::do_call::<&dyn core::ops::function::Fn<(), Output = i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe, i32>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panicking.rs:581:40
  32: std::panicking::catch_unwind::<i32, &dyn core::ops::function::Fn<(), Output = i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panicking.rs:544:19
  33: std::panic::catch_unwind::<&dyn core::ops::function::Fn<(), Output = i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe, i32>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panic.rs:359:14
  34: std::rt::lang_start_internal::{closure#0}
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/rt.rs:175:24
  35: std::panicking::catch_unwind::do_call::<std::rt::lang_start_internal::{closure#0}, isize>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panicking.rs:581:40
  36: std::panicking::catch_unwind::<isize, std::rt::lang_start_internal::{closure#0}>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panicking.rs:544:19
  37: std::panic::catch_unwind::<std::rt::lang_start_internal::{closure#0}, isize>
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/panic.rs:359:14
  38: std::rt::lang_start_internal
             at /rustc/55e86c996809902e8bbad512cfb4d2c18be446d9/library/std/src/rt.rs:171:5
  39: lang_start<core::result::Result<(), anyhow::Error>>
             at /Users/ika/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:205:5
  40: _main
```

</p>
</details> 

From what I traced, this happens during the resize redraw path:

`try_draw()` -> `autoresize()` -> `resize()` -> `clear()` -> `get_cursor_position()` (introduced in https://github.com/ratatui/ratatui/pull/2320) -> `crossterm::cursor::position()`

Crossterm's `position()` writes a CPR (Cursor position report, `b"\x1B[6n"`) query to stdout and then waits on `stdin` for the reply, but that's problematic:

- Almost every TUI app already has a separate thread continuously reading `stdin` for key/mouse events, so this races with Ratatui.
- Crossterm only waits up to 2 seconds for the CPR, which is fragile over slow SSH connections.
- That turns `draw()` into a potentially failing operation, while apps expect rendering to never fail unless something truly fatal happens, e.g. `stdout` being gone, which basically never happens.

## To Reproduce

1. Use the latest `main` branch of Ratatui.
2. Run a fullscreen TUI app with the `crossterm` backend. In my case [Yazi](https://github.com/sxyazi/yazi).
3. Use kitty as the terminal emulator.
4. Resize the terminal window while the app is actively rendering.
5. The app crashes with `The cursor position could not be read within a normal duration`.

## Expected behavior

Rendering during resize should not fail because Ratatui is trying to read the cursor position from `stdin`.

At minimum, a transient CPR failure should not make `draw()` fail thereby crashing the app.

## Are you willing to contribute a fix?

- [ ] I am willing to open a PR for this bug.
- [x] I can try to investigate, but I will need guidance.
- [ ] I am not able to work on a fix right now.

I'm not really sure how to fix it, since that cursor-position query looks like it was added on purpose to solve other issues, maybe those need a different/better solution? 

A more conservative way to go might be to temporarily revert [that commit](https://github.com/ratatui/ratatui/commit/720303e806b884f37f986913c111e79a4e243ae9) until the v0.30.1 release.

## Environment

- OS: macOS
- Terminal Emulator: kitty
- Font: SF Mono
- Crate version: latest `main` branch
- Backend: crossterm

### PR DESCRIPTION
**Pull request by orhun**
`Terminal::resize()` now clears without calling `get_cursor_position()`,
so that CPR (Cursor position report) calls does not interfere with
stdin.

Keeps `Terminal::clear()` semantics for explicit calls.

Fixes #2483

### CODE REVIEW

File: ratatui-core/src/terminal/buffers.rs [hunk 1]
```diff
@@ -117,11 +117,24 @@ impl<B: Backend> Terminal<B> {
...
-        let original_cursor = self.backend.get_cursor_position()?;
+        self.clear_viewport(true)
+    }
+
+    /// Clears according to the current viewport and resets the back buffer.
+    ///
+    /// When `preserve_cursor` is `true`, this snapshots and restores the backend cursor position.
+    /// When `false`, it skips cursor queries (useful in resize paths where querying the cursor can
+    /// fail on some backends).
+    pub(crate) fn clear_viewport(&mut self, preserve_cursor: bool) -> Result<(), B::Error> {
```
Comment (joshka) [inline ratatui-core/src/terminal/buffers.rs]: This `bool` parameter feels too opaque at the call site. `clear_viewport(true)` / `clear_viewport(false)` doesn’t communicate intent very well, and the Rust API Guidelines generally recommend avoiding boolean arguments when a more explicit API shape is possible: https://rust-lang.github.io/api-guidelines/type-safety.html#c-custom-type. I’m planning to split this so `clear_viewport()` just clears, and callers that need cursor preservation handle that explicitly.

File: ratatui-core/src/terminal/resize.rs [hunk 2]
```diff
@@ -40,7 +40,7 @@ impl<B: Backend> Terminal<B> {
         }
 
         self.set_viewport_area(next_area);
-        self.clear()?;
+        self.clear_viewport(false)?;
 
         self.last_known_area = area;
         Ok(())
```
Comment (joshka) [inline ratatui-core/src/terminal/resize.rs:49]: There’s a follow-up bug here for inline viewports: `clear_viewport()` moves the backend cursor to the viewport origin, so if `resize()` runs again before the next `draw()`, the next inline resize re-anchors from the wrong row. I’m planning to fix that by restoring the cursor position already returned by `compute_inline_size()` after the clear, which should preserve the resize behavior without adding another cursor query.

**Review by joshka — APPROVED** [review]

**Comment by joshka** [comment]
Pushed a couple of fixes for this that came up in review.
- bool param to more explicit code
- fix for inline resize (calling twice would reset the wrong cursor position)

**Comment by orhun** [comment]
Cool, thanks for making the changes
